gector_deberta_large:
    type: gector
    backend: triton
    serving_config:
        triton_hostname: localhost
        triton_port: 8001
        pretrained_model_name_or_path: "gotutiyan/gector-deberta-large-5k"
        triton_model_name: gector_deberta_large
        device: cpu # cpu, cuda, or auto

coedit_large:
    type: coedit
    backend: triton
    serving_config:
        triton_hostname: localhost
        triton_port: 8001
        pretrained_model_name_or_path: "grammarly/coedit-large"
        triton_model_name: coedit
        backend: ort
        device: cpu # cpu, cuda, or auto
    model_config:
        load_in_4bit: false
    model_inference_config:
        temperature: 0.8
    grammared_config:
        prompt_template: "Fix grammatical errors: {{ text }}"
        
